name: Build and Push Docker image

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  DOCKERHUB_USERNAME: "sgibson91"
  IMAGE_NAME: "binderhub-setup-gke"

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Docker image tag
        run: |

          if [ ${{ github.event_name }} = 'pull_request' ]; then
            echo "tag=test-${{ github.head_ref }}-$(openssl rand -hex 2)" >> $GITHUB_ENV
          else

            GIT_REF=$(echo ${{ github.ref }} | awk -F'/' '{print $3}')

            if [ $GIT_REF = 'main' ]; then
              echo "tag=latest" >> $GITHUB_ENV
            elif [[ $GIT_REF =~ (?<=v)[0-9]*\.[0-9]*\.[0-9]* ]]; then
              NEW_REF=$(echo $GIT_REF | sed 's/v//')
              echo "tag=$NEW_REF" >> $GITHUB_ENV
            fi

          fi

      - name: Confirm Docker image tag
        run: echo "Tag = ${{ env.tag }}"

      - name: Build and push
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.tag }}

      - name: Login to DockerHub
        if: github.event_name == 'push'
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        if: github.event_name == 'push'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.tag }}
